"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostVideoController = exports.createVideo = exports.videoController = exports.getAllVideoUseCase = void 0;
const CreateVideo_1 = require("../aplication/CreateVideo");
const GetAllVideoUseCase_1 = require("../aplication/GetAllVideoUseCase");
const createVideo_controller_1 = require("./createVideo-controller");
const createVideorepository_1 = require("./createVideorepository");
const video_controller_1 = require("./video-controller");
const video_repository_1 = require("./video-repository");
const videoRepository = new createVideorepository_1.InMemoryVideoRepository();
const getAllVideoUseCase = new GetAllVideoUseCase_1.GetAllVideo(videoRepository);
exports.getAllVideoUseCase = getAllVideoUseCase;
const videoController = new video_controller_1.VideoController(getAllVideoUseCase);
exports.videoController = videoController;
const videoRepositor = new video_repository_1.AddVideoRepository();
const createVideo = new CreateVideo_1.PostVideo(videoRepositor);
exports.createVideo = createVideo;
const PostVideoController = new createVideo_controller_1.CreateVideoController(createVideo);
exports.PostVideoController = PostVideoController;
